parameters:
# The Terraform Azure PowerShell container.
- name: Container
  type: string

jobs:
- job: BuildTestPublish
  displayName: Build, test and publish
  pool: $(DeploymentPool)
  container: ${{ parameters.Container }}
  workspace:
    clean: all
  steps:
  - checkout: self

  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: $(NodeVersion)

  - script: |
      npm ci
    displayName: npm restore
          
  - script: |
      npm run build
    displayName: npm build
          
  - script: |
      npm run test:unit
    continueOnError: false
    displayName: Unit test with Jest

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish unit test results
    inputs:
      testRunner: 'JUnit'
      testResultsFiles: 'junit.xml'
      testRunTitle: Unit Test Results

  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage results
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: 'coverage/'

  - task: PublishBuildArtifacts@1
    displayName: Publish angular app artifacts
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/dist'
      ArtifactName: AngularApp

  - task: PublishBuildArtifacts@1
    displayName: Publish deployment artifact
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/Deployment'
      ArtifactName: DeploymentScripts
